Repository Discord-or-Datcord/user, pull requests merged in 2024-07, with the labels that each got.

#6 Refactor/extract restful services
  app/src/main/java/io/datcord/app/Application.java
  commands/src/main/java/io/datcord/command/SlashCommandDispatcher.java
  events/src/main/java/io/datcord/api/package-info.java
  events/src/main/java/io/datcord/api/service/command/CommandService.java
  events/src/main/java/io/datcord/api/service/command/CommandServiceImpl.java
  events/src/main/java/io/datcord/api/service/command/package-info.java
  events/src/main/java/io/datcord/api/service/feature/package-info.java
  events/src/main/java/io/datcord/api/service/package-info.java
  events/src/main/java/io/datcord/event/EventDispatcher.java
  events/src/main/java/io/datcord/event/message/MessageReceivedEventListener.java
  events/src/main/java/io/datcord/event/message/registry/MessageReceivedEventListenerRegistry.java
  events/src/main/java/io/datcord/event/session/ReadyEventListener.java
  events/src/main/java/io/datcord/mapper/json/JsonMapper.java
  events/src/main/java/io/datcord/mapper/json/impl/SlashCommandJsonMapper.java
  events/src/main/java/io/datcord/mapper/package-info.java
  events/src/main/java/module-info.java
  feature/README.md
Labels: refactor

#7 bug: Fix issue with command data mapping
  command/ticket/src/main/java/io/datcord/command/ticket/TicketBoardEntitySelectInteractionEventListener.java
  events/src/main/java/io/datcord/event/session/ReadyEventListener.java
  events/src/main/java/io/datcord/mapper/json/impl/SlashCommandJsonMapper.java
Labels: bug

#9 refactor: refactor event handling
  app/pom.xml
  app/src/main/java/io/datcord/app/Application.java
  app/src/main/resources/services/io.datcord.event.EventSubscriber
  command/jira/pom.xml
  command/jira/src/main/java/io/datcord/command/jira/JiraSlashCommandEntitySelectionInteractionEventListener.java
  command/jira/src/main/java/io/datcord/command/jira/JiraSlashCommandListener.java
  command/jira/src/main/java/io/datcord/command/jira/package-info.java
  command/jira/src/main/java/module-info.java
  command/ticket/README.md
  command/ticket/src/main/java/io/datcord/command/ticket/TicketBoardButtonInteractionEventListener.java
  command/ticket/src/main/java/io/datcord/command/ticket/TicketBoardEntitySelectInteractionEventListener.java
  command/ticket/src/main/java/io/datcord/command/ticket/TicketSlashCommandListener.java
  command/ticket/src/main/java/io/datcord/command/ticket/package-info.java
  command/ticket/src/main/java/module-info.java
  command/ticket/src/main/resources/services/io.datcord.command.CommandModuleInitializer
  command/ticket/src/main/resources/services/io.datcord.event.EventModuleInitializer
  commands/src/main/java/io/datcord/command/SlashCommandDispatcher.java
  events/src/main/java/io/datcord/event/EventBusProvider.java
  events/src/main/java/io/datcord/event/EventDispatcher.java
  events/src/main/java/io/datcord/event/EventListener.java
  events/src/main/java/io/datcord/event/EventModuleInitializer.java
  events/src/main/java/io/datcord/event/EventSubscriber.java
  events/src/main/java/io/datcord/event/SubscriberRegistrar.java
  events/src/main/java/io/datcord/event/interaction/ButtonInteractionEventListener.java
  events/src/main/java/io/datcord/event/interaction/EntitySelectInteractionEventListener.java
  events/src/main/java/io/datcord/event/interaction/command/CommandAutoCompleteInteractionEventListener.java
  events/src/main/java/io/datcord/event/interaction/command/package-info.java
  events/src/main/java/io/datcord/event/interaction/dispatcher/ButtonInteractionEventDispatcher.java
  events/src/main/java/io/datcord/event/interaction/dispatcher/EntitySelectInteractionEventDispatcher.java
  events/src/main/java/io/datcord/event/interaction/registry/ButtonInteractionEventListenerRegistry.java
  events/src/main/java/io/datcord/event/interaction/registry/EntitySelectInteractionEventListenerRegistry.java
  events/src/main/java/io/datcord/event/message/MessageReceivedEventListener.java
  events/src/main/java/io/datcord/event/message/registry/MessageReceivedEventListenerRegistry.java
  events/src/main/java/module-info.java
  feature/jira_assignee_ping/pom.xml
  feature/jira_assignee_ping/src/main/java/io/datcord/feature/jap/JiraAssigneeWebhookMessageReceivedEventListener.java
  feature/jira_assignee_ping/src/main/java/io/datcord/feature/jap/JiraIssueWebhookMessageReceivedEventListener.java
  feature/jira_assignee_ping/src/main/java/io/datcord/feature/jap/package-info.java
  feature/jira_assignee_ping/src/main/java/module-info.java
  pom.xml
  util/src/main/resources/application.properties
Labels: refactor

#10 feat: Upgrade Jira assignee functionality and add Discord user mapping
  command/jira/src/main/java/io/datcord/command/jira/JiraSlashCommandEntitySelectionInteractionEventListener.java
  command/jira/src/main/java/io/datcord/command/jira/JiraSlashCommandListener.java
  command/jira/src/main/java/io/datcord/command/jira/ResponseBuilder.java
  command/jira/src/main/java/module-info.java
  events/src/main/java/io/datcord/event/session/ReadyEventListener.java
  events/src/main/java/io/datcord/mapper/json/JsonMapper.java
  events/src/main/java/io/datcord/mapper/json/impl/SlashCommandJsonMapper.java
  events/src/main/java/module-info.java
  feature/jira_assignee_ping/src/main/java/io/datcord/feature/jap/JiraAssigneeWebhookMessageReceivedEventListener.java
  feature/jira_assignee_ping/src/main/java/io/datcord/feature/jap/JiraAssociationDto.java
  feature/jira_assignee_ping/src/main/java/io/datcord/feature/jap/JiraAssociationMapper.java
  feature/jira_assignee_ping/src/main/java/io/datcord/feature/jap/JiraIssueWebhookMessageReceivedEventListener.java
  feature/jira_assignee_ping/src/main/java/module-info.java
Labels: enhancement

#11 bug; add missing webhook id
  feature/jira_assignee_ping/src/main/java/io/datcord/feature/jap/JiraAssigneeWebhookMessageReceivedEventListener.java
Labels: bug
